
# Apresentação

Os comissários da Infância e da Juventude do Tribunal de Justiça de Minas Gerais são servidores da justiça infantoadolescente que fazem parte dos serviços auxiliares específicos da Varas da Infância e da Juventude, conforme previsto no art. 150 do Estatuto da Criança e do Adolescente. Sua principal função é fornecer subsídios e apoio para a prestação jurisdicional adequada para essa parcela da população que goza de especial proteção constitucional.

O trabalho realizado na Vara Infracional da Infância e da Juventude, localizada no prédio do Centro Integrado de Atendimento ao Adolescente Autor de Infracional – CIA-BH, tem diversas peculiaridades ocasionadas pelo intenso fluxo de adolescentes, de familiares e de outros atores do Sistema de Garantia de Direitos (SGD) que circulam pelo prédio, pelo sistema de trabalho implementado no CIA-BH (que envolvem realização de audiências tanto na parte da manhã como na parte da tarde e plantões em dias não úteis e nos dias úteis fora do horário de expediente forense) e pela especialização da matéria envolvida. 

O corpo de comissários da Vara Infracional da Infância e da Juventude é integrado por servidores com formação em cursos superiores diversos, o que permite uma troca e integração de saberes e um atendimento mais qualificado aos adolescentes autores de atos infracionais e seus familiares, bem como as testemunhas e dos agentes do SGD que comparecem as instalações da Vara Infracional da Infância e da Juventude. Esse atendimento faz parte da função de apoio e acompanhamento das audiências judiciais, que ocorrem em todo horário de funcionamento do CIA-BH, isto é, nos períodos matutinos e vespertinos dos dias úteis e no período matutino nos fins de semana e feriados. 

Além de acompanhar as audiências, a equipe de comissários é responsável por realizar  a entrega dos adolescentes aos responsáveis presentes no CIA-BH ou à SUASE (em caso de acautelamento), bem como pelos encaminhamentos desses adolescentes determinados em audiência para os órgãos que ficam dentro do próprio CIA-BH, como o Núcleo de Atendimento às medidas socioeducativas e protetivas do Município de Belo Horizonte (NAMSEP) – local onde os adolescentes são acolhidos e é feito sua vinculação aos serviços socioassistenciais da capital mineira – e o Núcleo de Encaminhamento à Família (NEAF) de Belo Horizonte – órgão responsável para  entrega de adolescentes que foram apreendidos e desligados, mas que os familiares não puderam comparecer. Também é atribuição dessa equipe encaminhar os adolescentes aos órgãos externos como ao Conselho Tutelar ou a qualquer outro local determinado pelo magistrado.

Os comissários da Infância e da Juventude da Vara Infracional ainda fazem o acolhimento inicial nos casos em que há indicação de encaminhamento para Justiça Restaurativa. A equipe está sendo capacitada para atuar como facilitadores nos círculos restaurativos, sendo que alguns servidores já atuam junto ao Centro de Apoio à Justiça Restaurativa – CEAJUR, órgão do TJMG criado pela Resolução TJMG n. 971/2021.

Diante da necessidade de atendimento da Resolução CNJ n 77/2009^[Além da Resolução CNJ n. 77/2009, a ação da equipe é exercida em consonância com diversos diplomas normativos, como o art. 95 da Lei n. 8.069, de 1990; a Resolução CNJ n. 96/2009, que institui os Grupos de Monitoramento e Fiscalização do Sistema Carcerário (GMFs); o disposto na Lei 12.106/2009, que institui o Departamento de Monitoramento e Fiscalização do Sistema Carcerário e do Sistema de Execução de Medidas Socioeducativas (DMF) e a Resolução CNJ n. 214/2015, que dispõe sobre a organização e o funcionamento dos GMFs nos Tribunais de Justiça dos Estados, do Distrito Federal e dos Territórios e nos Tribunais Regionais Federais e o disposto na Lei n 12.594, de 18 de janeiro de 2012, que institui o Sistema Nacional de Atendimento Socioeducativo e regulamenta a execução das medidas socioeducativas destinadas a adolescente que pratique ato infracional.], que exige dos juízes das Varas da Infância e da Juventude com competência para a matéria referente à execução das medidas socioeducativas, a realização de inspeções nas entidades que executam os programas socioeducativos em meio fechado  e em meio aberto, há uma equipe específica para atender essa exigência fiscalizatória. Esses servidores acompanham o magistrado em suas visitas e realizam diligências nas unidades socioeducativas com o intuito de colher as informações para subsidiar as decisões judiciais. Além disso, monitoram a situação das unidades de internação e casas de semiliberdade quanto as condições de salubridade, os corriqueiros eventos de segurança e as frequentes tentativas de autoextermínio e automartírio, dentre tantos outros quesitos.

\newpage
