# Equipe de fiscalização

Para além do trabalho diretamente ligado às audiências (custódia dos adolescentes, encaminhamento deles a instituições, hospitais e variados tipos de diligências), os comissários precisam atender aos serviços que se atrelam à edição de novas leis e resoluções, sobretudo as que dizem respeito ao sistema socioeducativo.

Há necessidade de atendimento às exigências fiscalizatórias da Resolução Nº 77, do CNJ, que determina aos juízes das Varas da Infância e da Juventude, com competência para a matéria referente à execução das medidas socioeducativas, que realizem inspeções nas Unidades de Internação, de Semiliberdade, e, bem assim, nos programas para cumprimento de medidas socioeducativas em meio aberto sob sua responsabilidade e adotem as providências necessárias para o seu adequado funcionamento. 

Amiúde, ainda que nos finais de semana e feriados, há diligências realizadas junto a tais unidades socioeducativas pelos comissários.

Dessarte, a equipe de fiscalização realiza diligências nas unidades socioeducativas no sentido de colher diversas informações para subsidiar as decisões judiciais. A garantia dos direitos dos adolescentes privados de liberdade, as condições de salubridade das unidades, os corriqueiros eventos de segurança e as frequentes tentativas de autoextermínio e automartírio, dentre tantos outros quesitos, são objetos de constante monitoramento por parte da equipe citada. O atual surto pandêmico tem exigido redobrado trabalho.

A ação da equipe é exercida em obediência a diversos textos normativos: o art. 95 da Lei n. 8.069, de 1990; o art. 1º, §1º, da Resolução CNJ n. 77, de 2009; a Resolução CNJ no 96/2009, que institui os Grupos de Monitoramento e Fiscalização do Sistema Carcerário (GMFs); o disposto na Lei 12.106/2009, que institui o Departamento de Monitoramento e Fiscalização do Sistema Carcerário e do Sistema de Execução de Medidas Socioeducativas (DMF) e a Resolução CNJ no 214/2015, que dispõe sobre a organização e o funcionamento dos GMFs nos Tribunais de Justiça dos Estados, do Distrito Federal e dos Territórios e nos Tribunais Regionais Federais e o disposto na Lei Federal nº 12.594, de 18 de janeiro de 2012, que institui o Sistema Nacional de Atendimento Socioeducativo e regulamenta a execução das medidas socioeducativas destinadas a adolescente que pratique ato infracional.
\newpage

